### PR TITLE
Throw error for no matching state

### PR DESCRIPTION
**Pull request by juliankrispel**
- [x] Throw an error when there is no matching state for a state transition.

### CODE REVIEW

**Comment by deltaidea** [comment]
Would be better to check for this during compilation once. Otherwise, 👍

**Comment by juliankrispel** [comment]
Ha. Looking at the tests it should already do that. Wondering why there wasn't an error thrown... let me check

Julian Krispel
UI Engineer & Consultant
http://reactrocket.com
+447988116178

**Comment by tjvr** [comment]
Yeah, moo should already warn you. Would you like to send a bug report? Can you provide steps to reproduce this? :)

**Comment by nathan** [comment]
Unnecessary, since we do the check at compile time and we don't like runtime costs.

**Comment by tjvr** [comment]
There is, as it turns out, a bug in the check. Fixed in b09251f.

**Comment by nathan** [comment]
[Oops](https://github.com/tjvr/moo/blame/0727cc3a6b476654f5df34ed8414ea72dff9f18a/moo.js#L203). Sorry.

**Comment by tjvr** [comment]
no worries :-)

**Pull request closed without merging**
