### PR TITLE
Remove feed() and add remaining()

### LINKED ISSUE #43: Remove feed()
Implementing a streaming API on top of a RegExp-based tokenizer is fraught with difficulty, as discussed in #36. It's not clear what to do when a token overlaps with a chunk boundary; should we:

1. Require users to feed chunks which are already split on token boundaries
2. Buffer input until we get a regex match that doesn't extend to the end of the buffer —which introduces unfortunate restrictions on the lexer definition.
3. Re-lex the entire input when we receive new data, and somehow notify the consumer to discard some (or all!) of the old tokens (ouch)
4. Throw everything away and write our own RegExp implementation from scratch; then we can directly query the FSM to see if the node we're on can transition past the next character!

Only (1) seems like a workable solution. Excepting (4) (!), the rest you can re-implement yourself on top of `reset()`. So I propose removing `feed()` and re-introducing `remaining()` [which would return `buffer.slice(index)`]. Thus Moo is a fast lexer core; people can extend it with hacky strategies as necessary. :-)

### PR DESCRIPTION
**Pull request by tjvr**
Closes #43.

### CODE REVIEW

**Comment by nathan** [comment]
What is `remaining()` good for?

**Comment by tjvr** [comment]
It's supposed to help implement the streaming strategies in #43. But now you mention it, I suppose you can workaround this by taking `token.index + token.size`, and keeping a copy of the buffer yourself.

**Comment by nathan** [comment]
So if you're using streams you'd now do the following?

```js
const lexer = moo.compile({ … })

fs.createReadStream(INPUT)
.pipe(split(…))
.pipe(new TransformStream({
  readableObjectMode: true,
  transform(chunk, encoding, cb) {
    lexer.reset(chunk.toString())
    for (const t of lexer) this.push(t)
    cb()
  }
})

```

**Comment by tjvr** [comment]
Yes, although you need to save() state between chunks and restore it.

**Pull request merged**
