### PR TITLE
Fix Lexer#has so it works with states and keywords

### LINKED ISSUE #47: has() doesn't work for stateful lexers
It should return True if it appears in any of the states, not just the start state.

### LINKED ISSUE #50: has() returns false for keyword tokens that aren't included in lexer.groups
```JS
const lexer = moo.compile({
  keyword: 'foo',
  identifier: /[a-z]+/
})
```

```JS
> lexer.has('keyword')
  false
> lexer.has('identifier')
  true
```

You haven't pushed the latest code to GitHub (npm is ahead of master). Here's a solution:

```JS
  Lexer.prototype.has = function(tokenType) {
    var stateKeys = Object.getOwnPropertyNames(this.states)
    for (var i = stateKeys.length; i--; ) {
      var state = this.states[stateKeys[i]];
      for (var j = state.groups.length; j--; ) {
        var group = state.groups[j]
        if (group.tokenType === tokenType) return true
        if (group.keywords) {
          var keywordKeys = Object.getOwnPropertyNames(group.keywords)
          for (var k = keywordKeys.length; k--; ) {
            var keyword = group.keywords[keywordKeys[k]]
            if (keyword.tokenType === tokenType) return true
          }
        }
      }
    }
    return false
  }
```

Tests

```JS
describe('has', () => {

  test('works with multiple states', () => {
    // Example from the readme.
    let lexer = moo.states({
      main: {
        strstart: {match: '`', push: 'lit'},
        ident:    /\w+/,
        lbrace:   {match: '{', push: 'main'},
        rbrace:   {match: '}', pop: 1},
        colon:    ':',
        space:    {match: /\s+/, lineBreaks: true},
      },
      lit: {
        interp:   {match: '${', push: 'main'},
        escape:   /\\./,
        strend:   {match: '`', pop: 1},
        const:    {match: /(?:[^$`]|\$(?!\{))+/, lineBreaks: true},
      },
    })
    expect(lexer.has('strstart')).toEqual(true)
    expect(lexer.has('ident')).toEqual(true)
    expect(lexer.has('interp')).toEqual(true)
    expect(lexer.has('main')).toEqual(false)
  })

  test('works with keywords', () => {
    let lexer = moo.compile({
      keyword: 'foo',
      identifier: /[a-z]+/
    })
    expect(lexer.has('keyword')).toEqual(true)
    expect(lexer.has('identifier')).toEqual(true)
    expect(lexer.has('')).toEqual(false)
    expect(lexer.has('foo')).toEqual(false)
  })

})
```

### PR DESCRIPTION
**Pull request by deltaidea**
Also add fancy tests.

Closes #50, closes #47.

### CODE REVIEW

**Comment by deltaidea** [comment]
Anything I could change or fix here?

**Comment by tjvr** [comment]
I'll have a look this evening—sorry! :-)

**Comment by tjvr** [comment]
This looks great, thanks :D

I tweaked the style of the code slightly—I gave you bad advice the first time round, sorry about that—but I'm really happy we fixed this, and I like how well it's tested!

**Comment by deltaidea** [comment]
Sure! It's important to keep the style consistent and not in the way of performance.

Thanks for the invite! I might not have much time, but I'd be happy to help with maintenance.

**Pull request merged**
