### PR TITLE
Make Lexer iterable if iterators are supported

### PR DESCRIPTION
**Pull request by nathan**
As per my comment in #24.

### CODE REVIEW

**Comment by nathan** [comment]
@tjvr I suppose another way to do this is to add `Lexer#next()` and just make `Lexer#@@iterator` return `this`. Not sure which you'd prefer.

**Comment by tjvr** [comment]
This is neat! I know very little about the iterable API, but since that test passes it seems like a fine thing to me.

> another way to do this is to add Lexer#next()

**Comment by tjvr** [comment]
> another way to do this is to add Lexer#next()

That seemed cleaner to me, until I realised I might prefer `next()` to `lex()`, and this would prevent that change!

**Comment by nathan** [comment]
> I know very little about the iterable API

In short: an [iterable](https://tc39.github.io/ecma262/#sec-iterable-interface) is anything with an `@@iterator` (i.e., `Symbol.iterator`) method that returns an iterator. An [iterator](https://tc39.github.io/ecma262/#sec-iterator-interface) is anything with a `next` method that returns `{value: any, done: boolean}`, so you can iterate through it like this:

```js
const it = [1, 2, 3][Symbol.iterator]()
let o
while (!(o = it.next()).done) {
  console.log(o.value)
}
```

Which is more or less what **for-of** does for you. There are some optional methods an iterator can have (`return` and `throw`), but we don't need them here.

> That seemed cleaner to me, until I realised I might prefer `next()` to `lex()`, and this would prevent that change.

Yep, that's one of the reasons I didn't do it that way.

**Pull request merged**
